AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM template for the cloud resume backend stack

Globals:
  Function:
    Timeout: 10
#  Api:
#    Cors:
#      # This only sets the ACA* headers on Preflight (OPTIONS) reqs. Our expected use case is a simple GET so no preflight occurs
#      # Instead, to allow Cross-Origin fetch from our frontend, we need to return these headers via code in the GET resp
#      AllowOrigin: "'https://resume.laripping.com'"
#      AllowMethods: "'GET'"

Resources:
  FetchVisitorsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: fetch_visitors/
      Handler: app.lambda_handler
      Runtime: python3.8
      Architectures:
        - x86_64
      Policies:
        - Statement:
            - Effect: Allow
              Action:
              - dynamodb:PutItem
              Resource: 'arn:aws:dynamodb:eu-west-2:614776424286:table/VisitorsSam'
            - Effect: Allow
              Action:
              - dynamodb:Scan
              Resource: 'arn:aws:dynamodb:eu-west-2:614776424286:table/VisitorsSam'
      Events:
        # Events that can trigger this function - here it's just an API call
        FetchApiEvent:
          Type: Api
          # This will create an implicit RestAPI resource
          Properties:
            Path: /fetch-update-visitor-count
            Method: get

  VisitorsTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    Properties:
      TableName: VisitorsSam
      AttributeDefinitions:
        - AttributeName: "IP"
          AttributeType: "S"
        - AttributeName: "UA"
          AttributeType: "S"
        - AttributeName: "test"
          AttributeType: "B"
      KeySchema:
        - AttributeName: "IP"
          KeyType: "HASH"
        - AttributeName: "UA"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: "2"
        WriteCapacityUnits: "2"
      TableClass: STANDARD

Outputs:
  # Define here what should be printed when the deployment finishes
  # ...this can be used to pass info to other stacks (eg in a CI/CD workflow)
  # ...or to click the final REST API endpoint created for an instant end2end test

  ApiCreated:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/fetch-update-visitor-count"
  FunctionCreated:
    Description: "Lambda Function ARN"
    Value: !GetAtt FetchVisitorsFunction.Arn
  IamRoleCreated:
    Description: "Implicit IAM Role created"
    Value: !GetAtt FetchVisitorsFunctionRole.Arn
    # !GetAtt is the Short form of the intrinsic function to get an attribute from a
    # resource defined (explicitly or implicitly) in the template
